"""Tests for Python client for LetPot hydroponic gardens."""

from datetime import datetime, time

from letpot.models import (
    AuthenticationInfo,
    CycleWateringMode,
    LetPotDeviceErrors,
    LetPotGardenStatus,
    LetPotWateringSystemStatus,
    LightMode,
    WateringReason,
)

AUTHENTICATION = AuthenticationInfo(
    access_token="access_token",
    access_token_expires=1738368000,  # 2025-02-01 00:00:00 GMT
    refresh_token="refresh_token",
    refresh_token_expires=1740441600,  # 2025-02-25 00:00:00 GMT
    user_id="a1b2c3d4e5f6a1b2c3d4e5f6",
    email="email@example.com",
)


DEVICE_STATUS_GARDEN = LetPotGardenStatus(
    errors=LetPotDeviceErrors(low_water=True),
    light_brightness=500,
    light_mode=LightMode.VEGETABLE,
    light_schedule_end=time(17, 0),
    light_schedule_start=time(7, 30),
    online=True,
    plant_days=0,
    pump_mode=1,
    pump_nutrient=None,
    pump_status=0,
    raw=[77, 0, 1, 18, 98, 1, 0, 1, 1, 1, 1, 0, 0, 7, 30, 17, 0, 1, 244, 0, 0, 0],
    system_on=True,
    system_sound=False,
    temperature_unit=None,
    temperature_value=None,
    water_mode=None,
    water_level=None,
)

DEVICE_STATUS_DI_IDLE = LetPotWateringSystemStatus(
    raw=[
        77,
        0,
        1,
        33,
        66,
        1,
        0,
        0,
        0,
        0,
        0,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        24,
        0,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    pump_mode=0,
    errors=LetPotDeviceErrors(low_water=False),
    wifi_state=0,
    pump_on=False,
    pump_manual_duration=3,
    pump_cycle_on=False,
    pump_cycle_frequency=24,
    pump_cycle_duration=3,
    pump_cycle_mode=CycleWateringMode.CONTINUOUS,
    pump_cycle_workinginterval=0,
    pump_cycle_restinterval=0,
    pump_cycle_skip_water=0,
    pump_works_end=None,
    pump_works_latest_reason=WateringReason.NO_RUN,
    pump_works_latest_time=None,
    pump_works_next_time=None,
)

DEVICE_STATUS_DI_MANUAL = LetPotWateringSystemStatus(
    raw=[
        77,
        0,
        1,
        33,
        66,
        1,
        0,
        0,
        1,
        1,
        0,
        3,
        0,
        0,
        0,
        132,
        0,
        0,
        24,
        0,
        3,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        49,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    pump_mode=1,
    errors=LetPotDeviceErrors(low_water=False),
    wifi_state=0,
    pump_on=True,
    pump_manual_duration=3,
    pump_cycle_on=False,
    pump_cycle_frequency=24,
    pump_cycle_duration=3,
    pump_cycle_mode=CycleWateringMode.CONTINUOUS,
    pump_cycle_workinginterval=0,
    pump_cycle_restinterval=0,
    pump_cycle_skip_water=0,
    pump_works_end=datetime(2026, 3, 1, 0, 2, 12),
    pump_works_latest_reason=WateringReason.MANUAL,
    pump_works_latest_time=datetime(2026, 2, 28, 23, 59, 11),
    pump_works_next_time=None,
)

DEVICE_STATUS_DI_CYCLE = LetPotWateringSystemStatus(
    raw=[
        77,
        0,
        1,
        33,
        66,
        1,
        0,
        0,
        1,
        1,
        0,
        3,
        0,
        0,
        0,
        123,
        1,
        0,
        12,
        0,
        5,
        1,
        0,
        30,
        0,
        15,
        3,
        0,
        0,
        0,
        57,
        0,
        0,
        168,
        132,
        0,
        0,
    ],
    pump_mode=1,
    errors=LetPotDeviceErrors(low_water=False),
    wifi_state=0,
    pump_on=True,
    pump_manual_duration=3,
    pump_cycle_on=True,
    pump_cycle_frequency=12,
    pump_cycle_duration=5,
    pump_cycle_mode=CycleWateringMode.INTERMITTENT,
    pump_cycle_workinginterval=30,
    pump_cycle_restinterval=15,
    pump_cycle_skip_water=0,
    pump_works_end=datetime(2026, 3, 1, 0, 2, 3),
    pump_works_latest_reason=WateringReason.CYCLE,
    pump_works_latest_time=datetime(2026, 2, 28, 23, 59, 3),
    pump_works_next_time=datetime(2026, 3, 1, 11, 59),
)
