---
name: Release

on:
  release:
    types:
      - published

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Poetry
        run: pipx install poetry
      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Set package version
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version,,}"
          version="${version#v}"
          poetry version --no-interaction "${version}"
      - name: Build package
        run: poetry build --no-interaction
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-release:
    runs-on: ubuntu-latest
    needs: build-release
    environment:
      name: release
      url: https://pypi.org/p/letpot
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@v1
      - name: Sign published artifacts
        uses: sigstore/gh-action-sigstore-python@v3
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
          release-signing-artifacts: true
